@isTest
public class fortuneRanktestclass {
    private static testmethod void myunittest(){
        Lead le= new Lead();
        Le.LastName='john smith';
        Le.Email='xyz@amazon.com';
        Le.Company='Amazon';
        Le.Status='Converted';
        Le.LeadSource='Direct';
        insert Le;
        
        FortuneRankDatabase__mdt fmd= new FortuneRankDatabase__mdt();
        fmd.Label='Amazon';
        fmd.DeveloperName='Amazon';
        fmd.ComponyName__c='amazon';
        fmd.Domain__c='amazon.com';
       
    }
}